version: '3.4'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shopify

  fpm:
    image: php:7.4.0-fpm
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - shopify

networks:
  shopify:
